name: CI

on:
- workflow_dispatch

jobs:
  bake_cache:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Prepare cache dir
      run: mkdir ./cache/
    - name: Bake the cache!
      id: setup
      uses: ./.github/actions/lib
      with:
        script: bake_cache
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cache
        path: |
          cache/*.picke.xz
